services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    container_name: my-api
    ports:
      - "5001:5001"
    volumes:
      - ./api:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: my-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
